import About from "./About"
import Contact from "./Contact"
import Footer from "./Footer"
import Header from "./Header"
import Home from "./Home"
import Login from "./Login"
import Register from "./Register"
import Profile from "./Profile"
import Subscription from "./Subscription"
import Uplaod from "./Upload"
import SideNavbar from "./sideNavbar"
export {About,Contact,Footer,Header,Home,Login,Register,Profile,Subscription,Uplaod,SideNavbar}